//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EftalModel", "FK__DailyStoc__TICKE__267ABA7A", "Ticker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceAnalysis.Ticker), "DailyStockPrice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceAnalysis.DailyStockPrice), true)]
[assembly: EdmRelationshipAttribute("EftalModel", "FK__DailyStoc__TICKE__276EDEB3", "Ticker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceAnalysis.Ticker), "DailyStockPrice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceAnalysis.DailyStockPrice), true)]

#endregion

namespace FinanceAnalysis
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EftalEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EftalEntities1 object using the connection string found in the 'EftalEntities1' section of the application configuration file.
        /// </summary>
        public EftalEntities1() : base("name=EftalEntities1", "EftalEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EftalEntities1 object.
        /// </summary>
        public EftalEntities1(string connectionString) : base(connectionString, "EftalEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EftalEntities1 object.
        /// </summary>
        public EftalEntities1(EntityConnection connection) : base(connection, "EftalEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DailyStockPrice> DailyStockPrices
        {
            get
            {
                if ((_DailyStockPrices == null))
                {
                    _DailyStockPrices = base.CreateObjectSet<DailyStockPrice>("DailyStockPrices");
                }
                return _DailyStockPrices;
            }
        }
        private ObjectSet<DailyStockPrice> _DailyStockPrices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ticker> Tickers
        {
            get
            {
                if ((_Tickers == null))
                {
                    _Tickers = base.CreateObjectSet<Ticker>("Tickers");
                }
                return _Tickers;
            }
        }
        private ObjectSet<Ticker> _Tickers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DailyStockPrices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDailyStockPrices(DailyStockPrice dailyStockPrice)
        {
            base.AddObject("DailyStockPrices", dailyStockPrice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tickers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTickers(Ticker ticker)
        {
            base.AddObject("Tickers", ticker);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EftalModel", Name="DailyStockPrice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DailyStockPrice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DailyStockPrice object.
        /// </summary>
        /// <param name="dailyStockPriceID">Initial value of the DailyStockPriceID property.</param>
        /// <param name="tICKER">Initial value of the TICKER property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="open">Initial value of the Open property.</param>
        /// <param name="high">Initial value of the High property.</param>
        /// <param name="low">Initial value of the Low property.</param>
        /// <param name="close">Initial value of the Close property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        /// <param name="adjClose">Initial value of the adjClose property.</param>
        public static DailyStockPrice CreateDailyStockPrice(global::System.Int32 dailyStockPriceID, global::System.Int32 tICKER, global::System.DateTime date, global::System.Double open, global::System.Double high, global::System.Double low, global::System.Double close, global::System.Int32 volume, global::System.Double adjClose)
        {
            DailyStockPrice dailyStockPrice = new DailyStockPrice();
            dailyStockPrice.DailyStockPriceID = dailyStockPriceID;
            dailyStockPrice.TICKER = tICKER;
            dailyStockPrice.Date = date;
            dailyStockPrice.Open = open;
            dailyStockPrice.High = high;
            dailyStockPrice.Low = low;
            dailyStockPrice.Close = close;
            dailyStockPrice.Volume = volume;
            dailyStockPrice.adjClose = adjClose;
            return dailyStockPrice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DailyStockPriceID
        {
            get
            {
                return _DailyStockPriceID;
            }
            set
            {
                if (_DailyStockPriceID != value)
                {
                    OnDailyStockPriceIDChanging(value);
                    ReportPropertyChanging("DailyStockPriceID");
                    _DailyStockPriceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DailyStockPriceID");
                    OnDailyStockPriceIDChanged();
                }
            }
        }
        private global::System.Int32 _DailyStockPriceID;
        partial void OnDailyStockPriceIDChanging(global::System.Int32 value);
        partial void OnDailyStockPriceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TICKER
        {
            get
            {
                return _TICKER;
            }
            set
            {
                OnTICKERChanging(value);
                ReportPropertyChanging("TICKER");
                _TICKER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TICKER");
                OnTICKERChanged();
            }
        }
        private global::System.Int32 _TICKER;
        partial void OnTICKERChanging(global::System.Int32 value);
        partial void OnTICKERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Open
        {
            get
            {
                return _Open;
            }
            set
            {
                OnOpenChanging(value);
                ReportPropertyChanging("Open");
                _Open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Open");
                OnOpenChanged();
            }
        }
        private global::System.Double _Open;
        partial void OnOpenChanging(global::System.Double value);
        partial void OnOpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double High
        {
            get
            {
                return _High;
            }
            set
            {
                OnHighChanging(value);
                ReportPropertyChanging("High");
                _High = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High");
                OnHighChanged();
            }
        }
        private global::System.Double _High;
        partial void OnHighChanging(global::System.Double value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Low
        {
            get
            {
                return _Low;
            }
            set
            {
                OnLowChanging(value);
                ReportPropertyChanging("Low");
                _Low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Low");
                OnLowChanged();
            }
        }
        private global::System.Double _Low;
        partial void OnLowChanging(global::System.Double value);
        partial void OnLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Close
        {
            get
            {
                return _Close;
            }
            set
            {
                OnCloseChanging(value);
                ReportPropertyChanging("Close");
                _Close = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Close");
                OnCloseChanged();
            }
        }
        private global::System.Double _Close;
        partial void OnCloseChanging(global::System.Double value);
        partial void OnCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.Int32 _Volume;
        partial void OnVolumeChanging(global::System.Int32 value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double adjClose
        {
            get
            {
                return _adjClose;
            }
            set
            {
                OnadjCloseChanging(value);
                ReportPropertyChanging("adjClose");
                _adjClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjClose");
                OnadjCloseChanged();
            }
        }
        private global::System.Double _adjClose;
        partial void OnadjCloseChanging(global::System.Double value);
        partial void OnadjCloseChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EftalModel", "FK__DailyStoc__TICKE__267ABA7A", "Ticker")]
        public Ticker Ticker1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__267ABA7A", "Ticker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__267ABA7A", "Ticker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ticker> Ticker1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__267ABA7A", "Ticker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__267ABA7A", "Ticker", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EftalModel", "FK__DailyStoc__TICKE__276EDEB3", "Ticker")]
        public Ticker Ticker2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__276EDEB3", "Ticker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__276EDEB3", "Ticker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ticker> Ticker2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__276EDEB3", "Ticker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ticker>("EftalModel.FK__DailyStoc__TICKE__276EDEB3", "Ticker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EftalModel", Name="Ticker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ticker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ticker object.
        /// </summary>
        /// <param name="tickerID">Initial value of the TickerID property.</param>
        /// <param name="tickerName">Initial value of the TickerName property.</param>
        public static Ticker CreateTicker(global::System.Int32 tickerID, global::System.String tickerName)
        {
            Ticker ticker = new Ticker();
            ticker.TickerID = tickerID;
            ticker.TickerName = tickerName;
            return ticker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TickerID
        {
            get
            {
                return _TickerID;
            }
            set
            {
                if (_TickerID != value)
                {
                    OnTickerIDChanging(value);
                    ReportPropertyChanging("TickerID");
                    _TickerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TickerID");
                    OnTickerIDChanged();
                }
            }
        }
        private global::System.Int32 _TickerID;
        partial void OnTickerIDChanging(global::System.Int32 value);
        partial void OnTickerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TickerName
        {
            get
            {
                return _TickerName;
            }
            set
            {
                OnTickerNameChanging(value);
                ReportPropertyChanging("TickerName");
                _TickerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TickerName");
                OnTickerNameChanged();
            }
        }
        private global::System.String _TickerName;
        partial void OnTickerNameChanging(global::System.String value);
        partial void OnTickerNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EftalModel", "FK__DailyStoc__TICKE__267ABA7A", "DailyStockPrice")]
        public EntityCollection<DailyStockPrice> DailyStockPrices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DailyStockPrice>("EftalModel.FK__DailyStoc__TICKE__267ABA7A", "DailyStockPrice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DailyStockPrice>("EftalModel.FK__DailyStoc__TICKE__267ABA7A", "DailyStockPrice", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EftalModel", "FK__DailyStoc__TICKE__276EDEB3", "DailyStockPrice")]
        public EntityCollection<DailyStockPrice> DailyStockPrices1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DailyStockPrice>("EftalModel.FK__DailyStoc__TICKE__276EDEB3", "DailyStockPrice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DailyStockPrice>("EftalModel.FK__DailyStoc__TICKE__276EDEB3", "DailyStockPrice", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
